yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@deck.gl/aggregation-layers@*":
    dependencies:
      "@babel/runtime": "*"
      "@luma.gl/core": "*"
      # Peer dependencies:
      "@deck.gl/core": "*"
      "@deck.gl/layers": "*"

  "@deck.gl/core@*":
    dependencies:
      "@babel/runtime": "*"

  "@deck.gl/geo-layers@*":
    dependencies:
      "@babel/runtime": "*"
      "@luma.gl/core": "*"
      # Peer dependencies:
      "@deck.gl/core": "*"
      "@deck.gl/layers": "*"
      "@deck.gl/mesh-layers": "*"

  "@deck.gl/json@*":
    dependencies:
      "@babel/runtime": "*"

  "@deck.gl/layers@*":
    dependencies:
      "@babel/runtime": "*"
      "@luma.gl/core": "*"
      "math.gl": "*"
      # Peer dependencies:
      "@deck.gl/core": "*"

  "@deck.gl/mesh-layers@*":
    dependencies:
      "@babel/runtime": "*"
      "@luma.gl/core": "*"
      "@luma.gl/webgl": "*"

  "@deck.gl/react@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/3d-tiles@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/csv@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/gis@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/gltf@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/images@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/math@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/mvt@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/tables@*":
    dependencies:
      "@babel/runtime": "*"

  "@loaders.gl/tiles@*":
    dependencies:
      "@babel/runtime": "*"

  "@luma.gl/core@*":
    dependencies:
      "@luma.gl/gltools": "*"

  "@luma.gl/experimental@*":
    dependencies:
      "@babel/runtime": "*"
      # Peer dependencies:
      "@loaders.gl/images": "*"
      "@luma.gl/engine": "*"
      "@luma.gl/gltools": "*"

  "@math.gl/polygon@*":
    dependencies:
      "@babel/runtime": "*"

  "baseui@*":
    dependencies:
      "styletron-standard": "*"

  "deck.gl@*":
    dependencies:
      "@babel/runtime": "*"

  "react-katex@*":
    dependencies:
      # Peer dependencies:
      "prop-types": "*"

  "sass-loader@*":
    dependencies:
      # Peer dependencies:
      "node-sass": "*"
